### ISSUE TITLE
UDM Pro and iOS / apple issue

### ISSUE THREAD

**Issue by justinbadal** [Control-D-Inc/ctrld#59]
See this post on Reddit: 

[Post on reddit](https://reddit.com/r/ControlD/comments/14dzchz/udmpro_ctrld_issue/) 

I have everything set up as normal and instructed per the config pages, but even with an entirely blank filter / block situation, I still get the lack of internet connection warning.

**Comment by justinbadal** [comment]
Forgot to add, I noticed on my Windows 11 box that is connected to the UDM Pro network there was a report of no internet in network status. So it seems the issue is not isolated to apple devices only.

**Comment by justinbadal** [comment]
@cuonglm that is correct.

**Comment by yegors** [comment]
@justinbadal We need to have a look at your account, please email help@controld.com and reference this thread.

**Comment by justinbadal** [comment]
@yegors thanks. I emailed the address.

**Comment by vudam991** [comment]
I have the same issue but with Asus Merlin router, seemed like only on iPhones

**Comment by yegors** [comment]
We reproduced the issue. Investigating.

**Comment by yegors** [comment]
Cause found: When Apple device joins a network, it queries for `captive.apple.com`. This domain bypasses the DOH configuration, and uses a native OS resolver (this is needed to make captive portals work). On a UDM/UDR, this request fails to resolve while ctrld is running, which causes the "No network connection" message. 

We will fix this.

**Comment by justinbadal** [comment]
Whoa! Thank you guys so much for working on this!

**Comment by nosuntoday** [comment]
New user: In the auto generated config of ctrld on my UDM I see the line

 'captive.apple.com' = []},

Nevertheless I still have the problem described here. So if it has been fixed it does not work on my side.

**Comment by cuonglm** [comment]
> New user: In the auto generated config of ctrld on my UDM I see the line
> 
> 
> 
>  'captive.apple.com' = []},
> 
> 
> 
> Nevertheless I still have the problem described here. So if it has been fixed it does not work on my side. 

This will only be fixed in next release of ctrld.

**Comment by yegors** [comment]
This is resolved in the latest release: https://github.com/Control-D-Inc/ctrld/releases/tag/v1.3.0

**Comment by mattmill98** [comment]
Unfortunately I'm still seeing this issue while running 1.3.0. iOS thinks there is no network when connected to my UDM-Pro running ctrld 1.3.0.

**Comment by yegors** [comment]
Are you sure you're running v1.3.0 with default configuration? We had multiple people confirm this is resolved, including ourselves.

**Comment by mattmill98** [comment]
Yep v1.3.0 and no config changes. Just re-pulled the binary and will see how it is over the next few days.

**Comment by cuonglm** [comment]
> Yep v1.3.0 and no config changes. Just re-pulled the binary and will see how it is over the next few days.

Do you use `--cd` flag or local config?

**Comment by mattmill98** [comment]
I just run sh -c 'sh -c "$(curl -sL https://api.controld.com/dl)" -s RESOLVER_ID_HERE' and that's it.

**Comment by yegors** [comment]
Can you SSH into your UDM and run: nslookup captive.apple.com

What's the output?

**Comment by mattmill98** [comment]
Sure, 
![image](https://github.com/Control-D-Inc/ctrld/assets/10357263/f06d42a9-07f5-4b13-a84a-019d43e948b1)

**Comment by cuonglm** [comment]
> Sure, ![image](https://user-images.githubusercontent.com/10357263/261659187-f06d42a9-07f5-4b13-a84a-019d43e948b1.png)

Could you show the content of `ctrld.toml`?

**Comment by cuonglm** [comment]
@mattmill98 After you uninstall ctrld, what's the output of `nslookup captive.apple.com`?

**Comment by mattmill98** [comment]
Here: 
![image](https://github.com/Control-D-Inc/ctrld/assets/10357263/8a9a4ad5-98ba-4d70-b444-3cf722439679)

**Comment by cuonglm** [comment]
Did you have any special config for `dnsmasq`? What's the DNS server that you use when ctrld uninstalled?

What's the content of `/etc/resolv.conf` (after uninstall ctrld)?

**Comment by yegors** [comment]
Please try a dev build using this install command:

```
sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)"'
```

Let us know if this resolved the issue.

**Comment by mattmill98** [comment]
This dev build appears to fix it as I can now nslookup captive.apple.com. Will let you know if I see any issues on my apple devices over the next few days.
![image](https://github.com/Control-D-Inc/ctrld/assets/10357263/622dd8b3-f79f-4bfd-9979-01b24c86c174)

**Comment by jglemza** [comment]
I was having this same issue with my Firewalla. The dev build appears to fix it.

**Comment by yunhao-jiang** [comment]
This issue still appears with ctrld 1.5.1, not totally clear what caused it. Installed using `sh -c 'sh -c "$(curl -sSL https://147.185.34.1/dl)" -s RESOLVER_ID forced'`

If `os.resolver` contains a cache, it won't happen immediately after ctrld is activated. After around 10 minutes, the issue begins.

Behavior:
```
❯ nslookup captive.apple.com
Server:         GATEWAY IP HERE
Address:        GATEWAY IP HERE#53

** server can't find captive.apple.com: SERVFAIL
```
Logs:
```
{"level":"info","time":"2026-05-31T16:51:59-07:00.917","message":"[0da9b1] QUERY: SOURCE_IP:52663 (MacBookPro) -> listener.0: A captive.apple.com"}
{"level":"debug","time":"2026-05-31T16:51:59-07:00.917","message":"[0da9b1] My Policy, no network, captive.apple.com -> [upstream.os]"}
{"level":"debug","time":"2026-05-31T16:51:59-07:00.918","message":"[0da9b1] os resolver query for captive.apple.com. with nameservers: [[fe80::4ae2:adff:fe00:2eb1]:53] public: []"}
```

In comparison, the log when it was working:
```
{"level":"info","time":"2026-05-31T16:47:10-07:00.714","message":"[5d0a42] QUERY: SOURCE_IP:43317 (MacBookPro) -> listener.0: A captive.apple.com"}
{"level":"debug","time":"2026-05-31T16:47:10-07:00.714","message":"[5d0a42] My Policy, no network, captive.apple.com -> [upstream.os]"}
{"level":"debug","time":"2026-05-31T16:47:10-07:00.714","message":"[5d0a42] os resolver query for captive.apple.com. with nameservers: [[fe80::4ae2:adff:fe00:2eb1]:53] public: [76.76.2.0:53]"}
```

It seems **only the last line differs**: the query that doesn't work is missing a "public ip" while the one works has a "public ip". What does this mean?

----
Also, would it be possible a "loop" is happening? (i.e. dnsmasq forwards to `ctrld`, `ctrld` forwards to `os.resolver`, but `os.resolver` is on 127.0.0.1:53, which then redirects to `ctrld`?)
```
root@UCG-Max:~# nslookup captive.apple.com
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find captive.apple.com: SERVFAIL
```
and at the same time, a new log entry appears on `ctrld` side:
```
{"level":"info","time":"2026-05-31T17:00:05-07:00.818","message":"[c33cc1] QUERY: 127.0.0.1:47732 (UCG-Max) -> listener.0: A captive.apple.com"}
{"level":"debug","time":"2026-05-31T17:00:05-07:00.818","message":"[c33cc1] My Policy, no network, captive.apple.com -> [upstream.os]"}
{"level":"debug","time":"2026-05-31T17:00:05-07:00.818","message":"[c33cc1] os resolver query for captive.apple.com. with nameservers: [[fe80::4ae2:adff:fe00:2eb1]:53] public: []"}
```
----
In case anyone is experiencing the same, this issue may also cause UniFi-managed captive portal to stop working on Apple devices, as Apple queries `captive.apple.com` and look for a redirect to happen. However, if `captive.apple.com` fails to resolve, no redirection is possible.

<details>
<summary>Config File (Auto-generated)</summary>

```
# AUTO-GENERATED VIA CD FLAG - DO NOT MODIFY

[listener]
  [listener.0]
    ip = '0.0.0.0'
    port = 5354

    [listener.0.policy]
      name = 'My Policy'
      rules = [
        {        'captive.apple.com' = []},
        {        'aircanadawifi.com' = []},
        {        'acwifi.com' = []},
        {        'gogoinflight.com' = []},
        {        'southwestwifi.com' = []},
        {        'singaporeair-krisworld.com' = []},
        {        'airborne.gogoinflight.com' = []},
        {        'aainflight.com' = []},
        {        'aa.viasat.com' = []},
        {        'deltawifi.com' = []},
        {        'wifi.delta.com' = []},
        {        'unitedwifi.com' = []},
        {        'shop.ba.com' = []},
        {        'alaskawifi.com' = []},
        {        'flyfi.com' = []},
        {        'wifi.airasia.com' = []},
        {        'wifi.sncf' = []},
        {        'wifi.tgv-lyria.com' = []},
        {        'freewlan.sbb.ch' = []},
        {        'register.onboard.eurostar.com' = []},
        {        'thalysnet.com' = []},
        {        'iceportal.de' = []},
        {        'vvm.mstore.msg.t-mobile.com' = []},
        {        'wifi.inflightinternet.com' = []},
        {        'captive.inflightinternet.com' = []},
        {        'airbornesecure.inflightinternet.com' = []},
        {        'ip.videotron.ca' = []},
        {        'wifi.united.com' = []},
        {        'etihadwi-fly.com' = []},
        {        'inflight-wifi.com' = []},
        {        'southwestwifi.com' = []},
        {        'wifi.cathaypacific.com' = []},
        {        'timhortonswifi.com' = []},
        {        'detectportal.firefox.com' = []},
        {        'portal.mist.com' = []},
        {        'wifi.connected.xfinity.com' = []},
        {        'vvm.ee.co.uk' = []},
        {        'wifi.tgvlyria.com' = []},
        {        'guestinternet.com' = []},
        {        '*.network-auth.com' = []},
        {        'secure.datavalet.io' = []},
        {        'login.cloud5.com' = []},
        {        'wirelessportal.americanexpress.com' = []},
        {        '*.globalreachtech.com' = []},
        {        'neverssl.com' = []}
      ]

[network]
  [network.0]
    name = 'Network 0'
    cidrs = ['0.0.0.0/0']

[upstream]
  [upstream.0]
    type = 'doh'
    endpoint = 'https://dns.controld.com/RESOLVER_ID_HERE'
    bootstrap_ip = '76.76.2.22'
    timeout = 5000
```

</details>
